name: Desktop build - Mac
on: push

jobs:
  build:
    name: Build Mac desktop app
    runs-on: macos-latest
    if: "contains(github.event.head_commit.message, 'desktop beta')"
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install deps (with cache)
        uses: bahmutov/npm-install@v1
      - name: Install build deps
        run: |
          brew install pkg-config cairo pango libpng jpeg giflib librsvg
      - name: Build app
        env:
          CSC_LINK: ${{ secrets.CSC_LINK }}
          CSC_KEY_PASSWORD: ${{ secrets.CSC_KEY_PASSWORD }}
          APPLEID: ${{ secrets.APPLEID }}
          APPLEIDPASS: ${{ secrets.APPLEIDPASS }}
        run: |
          yarn build-electron:mac
        working-directory: products/jbrowse-desktop
        - name: Set release version
        run: echo "RELEASE_VERSION=$(node -p "require('./package.json').version")" >> $GITHUB_ENV
        working-directory: products/jbrowse-desktop
      - name: Set beta release version
        run: echo "BETA_RELEASE_VERSION=$(node -p "require('./package.json').desktopBeta")" >> $GITHUB_ENV
        working-directory: products/jbrowse-desktop
      - name: Get release
        id: get_release
        uses: kaliber5/action-get-release@v1
        with:
          token: ${{ github.token }}
          tag_name: ${{ env.BETA_RELEASE_VERSION }}
          draft: true
      - name: Upload Mac build
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.get_release.outputs.upload_url }}
          asset_path: ./products/jbrowse-desktop/dist/jbrowse-desktop-${{ env.RELEASE_VERSION }}-mac.dmg
          asset_name: jbrowse-desktop-${{ env.BETA_RELEASE_VERSION }}-mac.dmg
          asset_content_type: application
