name: Pull Request

on: pull_request

jobs:
  lint:
    name: Lint on node 12 and ubuntu-latest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 12
        uses: actions/setup-node@v1
        with:
          node-version: '12'
      - name: Install deps and build (with cache)
        uses: bahmutov/npm-install@v1
      - name: Lint codebase
        run: yarn eslint --config .eslintrc.base.json --no-eslintrc --report-unused-disable-directives --max-warnings 0 --ext .js,.ts,.jsx,.tsx .

  format:
    name: Format on node 12 and ubuntu-latest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 12
        uses: actions/setup-node@v2
        with:
          node-version: '12'
      - name: Install deps and build (with cache)
        uses: bahmutov/npm-install@v1
      - name: Check codebase format
        run: yarn prettier --check .
