# Upload website
on:
  push:
    branches:
      - master
name: Upload website
jobs:
  build:
    name: upload_web
    runs-on: ubuntu-latest
    if: "contains(github.event.head_commit.message, 'update docs')"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2
      - name: Install deps
        run: yarn
      - run: |
          cd website/
          yarn
          yarn build
          cd docs/
          make pdf
          cp pdfcombined.md ../../
          cp titlemod.md ../../
          cp listings.tex ../../
          cd ..
      - uses: docker://pandoc/latex:2.9
        with:
          args: --listings -H listings.tex --toc -o products/website/jbrowse2.pdf titlemod.md pdfcombined.md
      - name: Upload
        run: |
          cd website/
          aws s3 sync build s3://jbrowse.org/jb2/
          aws s3 cp jbrowse2.pdf s3://jbrowse.org/jb2/
          aws cloudfront create-invalidation --distribution-id E13LGELJOT4GQO --paths "/jb2/*"
