# Upload website
on:
  push:
    branches:
      - main
name: Upload website
jobs:
  build:
    name: build-upload
    runs-on: ubuntu-latest
    if: "contains(github.event.head_commit.message, 'update docs')"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2
      - name: Install deps (with cache)
        uses: bahmutov/npm-install@v1
        with:
          working-directory: website
      - name: Build website
        run: |
          cd website/
          yarn build
          cd docs/
          make pdfcombined.md titlerev # generate the pdfcombined.md, run pandoc in docker in the next step
          cp pdfcombined.md ../../
          cp title_rev_*.md ../../
          cp listings.tex ../../
          cp disable_float.tex ../../
          cd ../../
          ln -s website/docs/img
          cat <<EOF > entrypoint.sh
          #!/bin/sh -l
          /opt/texlive/texdir/bin/x86_64-linuxmusl/tlmgr install pmboxdraw
          /usr/bin/pandoc --pdf-engine /opt/texlive/texdir/bin/x86_64-linuxmusl/pdflatex --listings -H listings.tex -H disable_float.tex --toc -o website/jbrowse2.pdf website/docs/title_rev_*.md pdfcombined.md
          EOF
          chmod +x entrypoint.sh
          cat entrypoint.sh
      - uses: docker://pandoc/latex:2.9
        with:
          entrypoint: /github/workspace/entrypoint.sh
      - name: Upload
        run: |
          cd website/
          aws s3 sync --delete build s3://jbrowse.org/jb2/
          aws s3 cp jbrowse2.pdf s3://jbrowse.org/jb2/
          aws cloudfront create-invalidation --distribution-id E13LGELJOT4GQO --paths "/jb2/*"
